### ISSUE TITLE
Add post_apply command

### ISSUE THREAD

**Issue by mootpt** [hootsuite/atlantis#100]
Add `post_apply` command. This functionality would be super helpful in terms of performing tests after deploying infrastructure.

**Comment by mootpt** [comment]
started working on this. seeing some strange behavior with `pre_apply` as well. I will work out what's wrong and also fix #57 while I am there

**Comment by anubhavmishra** [comment]
Yea we can help flush this out. Let me know what you find.

**Comment by mootpt** [comment]
left #57 alone. all output is in info logs

**Comment by anubhavmishra** [comment]
Fixed with: https://github.com/hootsuite/atlantis/pull/102
