### ISSUE TITLE
Production-Ready Deployment: SSL? Load balanced?

### ISSUE THREAD

**Issue by sprice-janrain** [hootsuite/atlantis#101]
I saw Mishra's ConfigMgmtCamp talk in Portland today, and this project is exactly what we'd been looking for.

A few questions as to running this in production:

1. The Production-Ready section makes no mention of SSL, but I assume there would be no issue hosting this behind an SSL-enabled proxy. Would that work?
1. Could Atlantis be hosted on multiple hosts behind a single load balancer? From my brief look at the code, it appears I'd have to work out a way to share the data dir that is used for the locking bolt database. Anything I'm missing?

**Comment by anubhavmishra** [comment]
@sprice-janrain yep! It would work with ssl. Assuming you are just going to proxy to atlantis server. 👍 
Currently we have support for running only one atlantis server instance. Is there a reason one server process won't satisfy your requests? Every request to the atlantis server is a go routine in the background.

**Comment by sprice-janrain** [comment]
Just in terms of HA, so it's always available. Thinking more about it now, I guess it's not a big deal. If Atlantis goes down for whatever reason, it'd be trivial to bring it back up.
