### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by raphink** [hootsuite/atlantis#105]
Is it planned to provide a Docker image for Atlantis, or is there one already?

**Comment by anubhavmishra** [comment]
yea we have a docker image we use internally at Hootsuite for atlantis. Yep, we should have one up on docker hub once we have finished reworking a bit of our build stuff on CircleCI.

**Comment by raphink** [comment]
Great, looking forward to it!

**Comment by anubhavmishra** [comment]
Just for record keeping. Comments on docker image for atlantis: https://github.com/hootsuite/atlantis-example/pull/3#issuecomment-321050938

**Comment by so0k** [comment]
I had a first go at a docker file (and tested it by running ngrok in front of it with docker-compose) - but I got stuck where it seems atlantis is not using the github token to clone the repository?

https://github.com/honestbee/atlantis/commit/f76eb19e62f2f42aa7441a0c2e6bf235cf9a363b#diff-fd8635a5248b5832a7faf06a8e572e17R37

**Comment by so0k** [comment]
I guess I can just generate a key pair for the atlantis github user and mount the private key into the atlantis container...

**Comment by elijah** [comment]
@so0k did you get this working?  I want to have a play but if you're already working on building an image that is reasonable, it seems silly to duplicate your work. :)

**Comment by anubhavmishra** [comment]
@so0k and @elijah I am currently working on: https://github.com/hootsuite/atlantis/issues/110 so should have that out today or tomorrow. Next up will be the docker image.

**Comment by ewright-rms** [comment]
Bump.

**Comment by so0k** [comment]
@ewright-rms & @elijah - read [changelog](https://github.com/hootsuite/atlantis/blob/master/CHANGELOG.md)
