### ISSUE TITLE
Set user agent for AWS interactions

### ISSUE THREAD

**Issue by nwalke** [hootsuite/atlantis#111]
I see the user agent in my cloudtrail logs as `aws-sdk-go/1.8.39 (go1.8.3; linux; amd64)`.  It would be nice if that included something about atlantis like terraform does: `aws-sdk-go/1.10.18 (go1.8; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.9.8`

**Comment by lkysow** [comment]
Since Atlantis no longer assumes roles itself (see #122) this no longer makes sense. Was a good idea though!
