### ISSUE TITLE
Support passing multiple AWS credentials

### ISSUE THREAD

**Issue by majormoses** [hootsuite/atlantis#112]
In the projects I am currently evaluating atlantis for we have chosen to have seperate aws accounts for production and provide no cross account access as a design choice. This is to reduce the number of people who can accidentally blow up something in prod when they thought it was dev. The people that have access to production are limited as much as possible and those that would have access to a full terraform plan and apply in production are further limited. The reason for this is I have seen more than once someone wipe out something in production and they thought it was dev.

I am not sure how I envision this being done but essentially what we are doing locally at the moment is relying on ENV vars to supply credentials and `awsenv` to safely store and switch between sets of credentials. I imagine that we would want to have a place that per environment, project, etc we could specify the credentials to be used.

**Comment by majormoses** [comment]
Now that I think about this it is not specific to amazon other providers could certainly fall into the same limitation.

**Comment by nwalke** [comment]
It would be really nice to specify the IAM role I want Atlantis to assume in my atlantis.yml file.

**Comment by anubhavmishra** [comment]
@nwalke I like that idea. I am also wondering if having people specify an assume role in terraform is better? For example:
```hcl
provider "aws" {
  assume_role {
    role_arn     = "arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME"
    session_name = "SESSION_NAME"
    external_id  = "EXTERNAL_ID"
  }
}
```

**Comment by nwalke** [comment]
@anubhavmishra I was doing that but switched to Atlantis assuming the role to get that amazing GitHub user name in my CloudTrail logs :D

I think that feature is amazing and would love to keep it if possible.  Not sure how to do that with the Terraform role assumption.

**Comment by anubhavmishra** [comment]
yea, the cloudtrail stuff is awesome! Alright, will get a proposal out for this and lets see if that works with other cloud providers in the future.

**Comment by lkysow** [comment]
@nwalke in #122 we've added the ability to reference the `atlantis_user` variable in your assume-role config block:

```hcl
provider "aws" {
  assume_role {
    role_arn     = "arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME"
    session_name = "${var.atlantis_user}"
  }
}
```

We execute `plan` and `apply` with `-var atlantis_user=$github-user`.

This way, Atlantis doesn't need to deal with assuming roles and everyone can use the normal Terraform way for handling this. This will allow for multi-account usage without any changes on the Atlantis side.

Will this work for you?

**Comment by nwalke** [comment]
Yes, a much better solution!
