### ISSUE TITLE
GHE Support

### ISSUE THREAD

**Issue by kennyg** [hootsuite/atlantis#116]
I'd like to test this out internally against a github enterprise instance. would be awesome to have that option.

**Comment by anubhavmishra** [comment]
Atlantis works for GHE . We use it at Hootsuite. Use the GitHub host argument while starting atlantis server .

**Comment by anubhavmishra** [comment]
Atlantis works for GHE . We use it at Hootsuite. Use the GitHub host argument while starting atlantis server .
