### ISSUE TITLE
Atlantis won't pass parameters to terraform

### ISSUE THREAD

**Issue by damascenorakuten** [hootsuite/atlantis#151]
Hello everyone. I'm currently using the latest version of Atlantis (0.1.2) and terraform (0.10.6). I am trying to connect to MySQL to create a user via mysql provider. Here's my code:
```
# Variables
variable "db-admin-encrypted-password" {
  default = "ENCRYPTED_PASSWORD"
}

# Decrypt passwords
data "external" "db-admin-password" {
  program = ["bash", "../../scripts/decrypt.sh", "${var.db-admin-encrypted-password}"]
}

# MySQL connection
provider "mysql" {
  endpoint = "db-server.example.com:3306"
  username = "mysqladmin"
  password = "${data.external.db-admin-password.result.password}"
}
```

This is a bug from terraform, to resolve it temporarily I need to execute plan/apply with the parameter **-input=false** but here's what happens when I do that:

```
exit status 1: running "terraform plan -refresh -no-color -out /home/atlantis/.atlantis/repos/wuakitv/terraform/93/default/rds/development01-wuaki/default.tfplan -var atlantis_user=damascenorakuten -input=\"false\"" in "/home/atlantis/.atlantis/repos/wuakitv/terraform/93/default/rds/development01-wuaki": 
invalid boolean value "\"false\"" for -input: strconv.ParseBool: parsing "\"false\"": invalid syntax
Usage: terraform plan [options] [DIR-OR-PLAN]
````

I also tried to use **--target** and it works when **atlantis plan** is run but it doesn't work on **atlantis apply**, so I would like to make sure I can run atlantis with terraform parameters, such as -input and --target.

Thanks

**Comment by lkysow** [comment]
Hi @damascenorakuten, for your first issue with `-input="false"` if you run with `-input=false` (without the quotes) it should work.

For the second issue with `-target` I've reproduced and fixed it in `master`. I'll comment back here when we release a new version, until then you can compile it from master.

**Comment by damascenorakuten** [comment]
Thank you

**Comment by lkysow** [comment]
@damascenorakuten sorry I never got back to you about the release. This is in the latest release now.
