### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by nadavshatz** [hootsuite/atlantis#191]
Hey guys,

Any chance to get 0.1.3 released?
I'd love to get that tag in docker hub and use atlantis with terraform 0.10.8.

I got #186 merged for that.

Please let me know if there is anything else i can do to assist.

Cheers

**Comment by lkysow** [comment]
Hi @nadavshatz thanks! I'll get to this ASAP.

**Comment by nadavshatz** [comment]
Thanks @lkysow 🍻

**Comment by lkysow** [comment]
New release is up! FYI we push master to docker hub on every master merge, so `hootsuite/atlantis:latest` had the docker image with the terraform version.

See tag 0.1.3 here: https://hub.docker.com/r/hootsuite/atlantis/tags/

**Comment by nadavshatz** [comment]
Thanks again!
