### ISSUE TITLE
Bridging Packer and Terraform

### ISSUE THREAD

**Issue by horsey** [hootsuite/atlantis#208]
Hello, 
As I try to build a pipe of for my Infrastructure deployment, I see the need to have a central broker helping Packer and Terraform to talk to each other; As of now, they can't talk to each other directly. 

As I understand  Hashicorp proposes that one does this with their Atlas - which I can't afford. 

I didn't see this any where, but can Atlantis achieve this?

**Comment by lkysow** [comment]
Atlantis doesn't integrate with Packer right now. What specific functionality are you looking for?

**Comment by horsey** [comment]
I want to the AMI IDs generated by Packer to be served as an input to the Terraform to build a pipeline.  I believe this is achieved with Hashicorp's Atlas.

**Comment by lkysow** [comment]
Okay gotcha, so something like this: https://www.terraform.io/docs/enterprise/artifacts/artifact-provider.html?

I think this is a bit out of the scope for Atlantis at least at the moment. For now, I'd recommend using a normal `data` source and just looking up the latest AMI ID with a certain tag as recommended here: https://www.terraform.io/docs/configuration/data-sources.html

```
# Find the latest available AMI that is tagged with Component = web
data "aws_ami" "web" {
  filter {
    name   = "state"
    values = ["available"]
  }

  filter {
    name   = "tag:Component"
    values = ["web"]
  }

  most_recent = true
}
```

**Comment by horsey** [comment]
Ah, that's what I need I think. Thanks for the idea!
