### ISSUE TITLE
Expired Certificate (atlantis.run)

### ISSUE THREAD

**Issue by bitnovus** [hootsuite/atlantis#209]
It looks like the certificate expired on 11/24.

**Comment by lkysow** [comment]
Thanks! We're on it.

**Comment by anubhavmishra** [comment]
@bitnovus just renewed the cert! 
![image](https://user-images.githubusercontent.com/4024506/33395402-3de38c58-d4fa-11e7-9305-127a6ef353db.png) 🎉
