### ISSUE TITLE
Built-in SSL support?

### ISSUE THREAD

**Issue by natemueller** [hootsuite/atlantis#225]
My team is looking at Atlantis and was curious if there's a reason you recommend standing up nginx (or similar) to handle SSL vs doing it in the app itself.  We'd be happy to contribute a patch if you're interested but it seems like a very simple change and I wanted to check first to see if there's some reason behind the current behavior.

**Comment by lkysow** [comment]
Hi Nate,

No reason other than I haven't got to it yet. I'd love it if you submitted
a patch!
