### ISSUE TITLE
GitLab - Issue when passing --gitlab-hostname param

### ISSUE THREAD

**Issue by jrasell** [hootsuite/atlantis#227]
Hi; first of all thanks for this project it looks amazing and I am in the process of testing it out for use with a GitLab enterprise installation. I am running atlantis docker version `0.2.2` with the following command args:

```
server --atlantis-url atlantis.<REDACTED> --gitlab-hostname <REDACTED> --gitlab-user <REDACTED> --gitlab-token <REDACTED>
```

The server starts up correctly and I have configured GitLab tokens as detailed within the README.md. When creating a test merge request on my Terraform repository and commenting with `atlantis plan`, Atlantis logs the following error:

```
2018/01/12 13:23:52 [ERROR] <REDACTED>#36: Making merge request API call to GitLab: GET https://gitlab.com/api/v4/projects/<REDACTED>/merge_requests/36: 401 {message: 401 Unauthorized}
```

It seems the flag `--gitlab-hostname` is not overriding the default, unless I am getting something wrong. Any help would be appreciated.

**Comment by cooling75** [comment]
Hi, we ran in to the same problem. Looks like in server.go:106
			`Client: gitlab.NewClient(nil, config.GitlabToken)`
the "nil" should not be there? Maybe config.GitlabHostname instead?

**Comment by jrasell** [comment]
@cooling75 It seems the `gitlab.NewClient` doesn't accept a base URL argument. I believe using the `SetBaseURL(urlStr string)` function within the GitLab package may do the trick. If I get a chance I will try and push a fix sometime soon.

**Comment by anubhavmishra** [comment]
@jrasell thanks for the feedback and the PR!
